apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
  namespace: django-app
data:
  DJANGO_SETTINGS_MODULE: "EasyTPCloud.settings.production"
  DB_HOST: "postgresql-service"
  DB_PORT: "5432"
  DB_NAME: "django_db"