apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - serviceaccount.yaml
  - role.yaml
  - rolebinding.yaml
  - cleanup-rbac.yaml
  - configmap.yaml
  - nginx-configmap.yaml
  - postgresql.yaml
  - redis.yaml
  - django-deployment.yaml
  - nginx-deployment.yaml
  - ingress.yaml